[package]
name = "salty_sailor"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.42.0", features = ["full"] }
dotenv = "0.15.0"
rand = "0.8.5"
ethers = "2.0.14"
indicatif = "0.17.9"

[[bin]]
name = "salty_sailor"
path = "src/main.rs"
