default_job = "run-hunter"

[env]
CARGO_TERM_COLOR = "always"
RUST_BACKTRACE = "1"

# Fast check for syntax errors
[jobs.check]
command = ["cargo", "check"]
need_stdout = false

# Main hunting job with optimized parameters
[jobs.run-hunter]
command = [
    "cargo", "run", "--release", "--",
    "--start-pattern", "000000000000",  # Matched to your default of 12 zeros
    "--min-zeros", "12",                # Restored to original value
    "--step", "50000",                  # Restored to original value
    "--log-interval", "15000",          # Restored to original value
    "--max-tries", "10000000000",       # Added max tries
    "--skip-confirmation"
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

# Performance testing jobs
[jobs.bench]
command = ["cargo", "bench"]
need_stdout = true

[jobs.test-all]
command = ["cargo", "test", "--all-targets"]
need_stdout = true

[jobs.clippy-all]
command = ["cargo", "clippy", "--all-targets", "--", "-D", "warnings"]
need_stdout = true

[keybindings]
r = "job:run-hunter"  # Quick restart of hunter
b = "job:bench"       # Quick benchmark
t = "job:test-all"    # Run all tests
c = "job:clippy-all"  # Run clippy
