services:
  hash_hunter:
    build: .
    volumes:
      - hash_hunter_data:/usr/src/app/gen
    command: -p 69 -e 69696969 -c -s 100000 -m 100000000000 -i 10000 -y
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '7.5'
          memory: 8G

volumes:
  hash_hunter_data:
    driver: local