services:
  hash_hunter:
    image: hash_hunter:latest
    build:
      context: .
    volumes:
      - ./gen:/usr/src/app/gen
    command: hash_hunter -p 69 -e 6969 -c -s 100000 -m 100000000000 -i 10000 -y
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "7.5"
          memory: 8G
    healthcheck:
      test: ["CMD", "supervisorctl", "status", "hash_hunter"]
      interval: 30s
      timeout: 10s
      retries: 3
