version: '3.8'
services:
  hash_hunter:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ..:/workspaces/hash_hunter:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    command: sleep infinity
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 15.5G

  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: hunter
      POSTGRES_DB: hunter_db

volumes:
  postgres-data:
