[build]
builder = "dockerfile"
dockerfilePath = "cloud_methods/railway/Dockerfile.railway"

# Consolidate services into a single service with multiple replicas
[[services]]
name = "hash-hunter"
replicas = 5
command = "hash_hunter -p 000000000000 -c -s 100000 -m 100000000000 -i 10000 -y"

[deploy]
strategy = "rolling"
healthcheck = true
healthcheckPath = "/health/index.html"
healthcheckTimeout = 3
healthcheckInterval = 5
restartPolicy = "on-failure"