[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./hash_hunter -p 000000000000 -c -s 100000 -m 100000000000 -i 10000 -y"
restartPolicyType = "on-failure"
numReplicas = 4

[service]
internal_port = 6379