version: '3.8'
services:
  hash-hunter:
    image: hash-hunter
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: on-failure
    volumes:
      - ./gen:/app/gen
    command: -p 000000000000 -c -s 100000 -m 100000000000 -i 10000 -y
    ports:
      - "6379:6379"
volumes:
  results:
    driver: local
