name: Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install loguru eth_account ruff pytest
        
    - name: Lint with Ruff
      run: |
        ruff check .
        
    - name: Test Address Generator
      run: |
        python src/main.py -p "123" -e "456" -c --max-tries 1000 --step 100